name: CI/CD Pipeline for FastAPI

on:
  push:
    branches:
      - main
      - staging
      - development
  pull_request:
    branches:
      - main
      - staging
      - development

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings

  build-and-push:
    name: Build & Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        # with:
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          # docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:staging .
          # docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:staging

      - name: Build and push Docker image (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          # docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          # docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    steps:
      - name: SSH and Deploy (Staging)
        if: github.ref == 'refs/heads/staging'
        uses: appleboy/ssh-action@v0.1.6
        # with:
        #   host: ${{ secrets.STAGING_SERVER_HOST }}
        #   username: ${{ secrets.STAGING_SERVER_USER }}
        #   password: ${{ secrets.STAGING_SERVER_PASSWORD }}
        #   script: |
        #     docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:staging
        #     docker stop fastapi-app-staging || true
        #     docker rm fastapi-app-staging || true
        #     docker run -d -p 8001:8000 --name fastapi-app-staging ${{ secrets.DOCKER_USERNAME }}/fastapi-app:staging

      - name: SSH and Deploy (Production)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.6
        # with:
        #   host: ${{ secrets.PRODUCTION_SERVER_HOST }}
        #   username: ${{ secrets.PRODUCTION_SERVER_USER }}
        #   password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
        #   script: |
        #     docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
        #     docker stop fastapi-app || true
        #     docker rm fastapi-app || true
        #     docker run -d -p 8000:8000 --name fastapi-app ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
